steps:
  - id: 'install dependencies'
    name: 'bitnami/git:latest'
    args: ['clone', 'https://github.com/ozonep/gitea-monaco']
    dir: 'cloudbuilder'


  - id: 'install dependencies'
    name: 'bitnami/git:latest'
    args: ['fetch', '--tags', '--force']
    dir: 'cloudbuilder'

  - id: 'build and push container'
    name: 'gcr.io/kaniko-project/executor:latest'
    args: [
      '--context=dir://cloudbuilder/',
      '--destination=gcr.io/$PROJECT_ID/giteamonaco',
      '--cleanup',
    ]
