steps:
  - id: 'build and push container'
    name: 'gcr.io/kaniko-project/executor:latest'
    timeout: 1500s
    args: [
      '--context=dir://cloudbuilder/gitea-monaco',
      '--destination=gcr.io/$PROJECT_ID/giteamonaco',
      '--cleanup',
    ]
